version: '3'

services:
  app:
    image: node:8
    ports:
      # - "3000:3000"
      - "9009:9009"
    volumes:
      - .:/app
    working_dir: /app
    # command: /bin/sh -c "yarn && (npm start & npm run storybook & wait)"
    command: /bin/sh -c "yarn && npm run storybook"
    # command: yarn storybook
